version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "calsynctestsamappstackname"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nrzp0gkek5dm"
s3_prefix = "calsynctestsamappstackname"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
