AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  calSyncLambda

  Sample SAM Template for calSyncLambda
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs14.x
    Environment:
      Variables:
        CLIENT_ID: your client id here
        CLIENT_SECRET: your client secret here
        WEBHOOK_URL: your webhook url here
        SUBSCRIPTION_SECRET: your subscription secret here
        TENANT_ID: your azure AD tenant ID here
        CALENDAR_OWNER_UPN: your calendar anchor UPN here
        CALENDAR_GROUP_NAME: your calendar group name here
        GROUP_EMAIL_PREPEND: your random string here

Resources:
  WebhookService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: subscription-refresh/dist
      Handler: dist/WebhookService.lambdaHandler
      Environment: 
        Variables:
          WEBHOOK_RESPONDER_NAME: !Ref WebhookResponder
      Events: 
        Webhook:
          Type: Api
          Properties:
            Path: /Webhooks/{webhookType}
            Method: post
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref WebhookResponder
  SubscriptionRefreshService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: dist/SubscriptionService.lambdaHandler
      Events:
        RefreshEvery12hrs:
          Type: Schedule
          Properties:
            Schedule: rate(12 hours)
  WebhookResponder:
      Type: AWS::Serverless::Function
      Properties:
        Handler: dist/WebhookResponder.lambdaHandler
      


Outputs:
  WebhookService:
    Description: 'API Gateway endpoint URL for Prod stage CalSync'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Webhooks/'
  